version: '3.7'

services:
    e2e:
        build: ./e2e
        volumes:
            - ./e2e/cypress:/e2e/cypress
            - /e2e/node_modules
        environment: 
            WAIT_HOSTS: mongo:27017, es:9200, server:8080, rabbitmq:5672
            WAIT_HOSTS_TIMEOUT: 300
            WAIT_SLEEP_INTERVAL: 30
            WAIT_HOST_CONNECT_TIMEOUT: 30 
        networks:
            - intersect-backend  

networks:
    intersect-backend:
        external:
            name: intersect-backend    