FROM golang:alpine as builder

ARG build_dir

RUN mkdir /build
WORKDIR /build
COPY . .
RUN \ 
    go get -d -v \
    && go install -v \
    && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main "${build_dir}"

FROM scratch

COPY --from=builder /build /app

WORKDIR /app

CMD ["./main"]